version: "3.8"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode-2  # Change this name
    restart: always
    ports:
      - "9871:9870"
      - "9001:9000"
    environment:
      - CLUSTER_NAME=demo
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_namenode_http_address=namenode:9870
    volumes:
      - namenode-data:/hadoop/dfs/name
    networks:
      - hadoop-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-2 # Change this name
    restart: always
    ports:
      - "9865:9864"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_datanode_address=0.0.0.0:9866
      - HDFS_CONF_dfs_datanode_http_address=0.0.0.0:9864
      - HDFS_CONF_dfs_client_use_datanode_hostname=true
      - HDFS_CONF_dfs_datanode_hostname=datanode
      - HDFS_CONF_dfs_datanode_use_datanode_hostname=true
    volumes:
      - datanode-data:/hadoop/dfs/data
    networks:
      - hadoop-net
    depends_on:
      - namenode

  crud-app:
    build: .
    container_name: crud-app-2 # Change this name
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - hadoop-net
    depends_on:
      - namenode
      - datanode

volumes:
  namenode-data:
  datanode-data:

networks:
  hadoop-net:
    driver: bridge
